import { defineConfig, devices } from '@playwright/test';

/**
 * Address of the application under test.
 *
 * By default we test an instance started locally (or on the CI runner). Setting `BASE_URL`
 * points the whole suite at any other environment - and that single variable is the only
 * difference between "testing on the runner" and "testing a deployed environment".
 */
const baseURL = process.env.BASE_URL ?? 'http://localhost:3000';

export default defineConfig({
  testDir: './tests',
  timeout: 30_000,
  expect: { timeout: 5_000 },
  fullyParallel: true,

  // One worker on CI. This line is inherited from the config generated by
  // `npm init playwright` and in most projects nobody ever revisits it - even though the
  // runner has four cores. We come back to it in EXERCISE 10.
  workers: process.env.CI ? 1 : undefined,

  // No retries. Right now every flaky test is a red build - EXERCISE 12.
  retries: 0,

  reporter: [['list'], ['html', { open: 'never' }]],

  use: {
    baseURL,
    // Trace everything, always. Convenient, but artifacts balloon - EXERCISE 15.
    trace: 'on',
    screenshot: 'only-on-failure',
  },

  // The server starts only when no external environment is given.
  // The build is no longer here: the application is built once, in its own job, and
  // arrives as an artifact. A compilation error now fails the build job, where it belongs,
  // instead of masquerading as a broken test.
  webServer: process.env.BASE_URL
    ? undefined
    : {
        command: 'npm start',
        url: 'http://localhost:3000/api/health',
        reuseExistingServer: !process.env.CI,
        timeout: 120_000,
      },

  projects: [
    {
      name: 'api',
      testDir: './tests/api',
      use: { baseURL },
    },
    {
      name: 'ui-chromium',
      testDir: './tests/ui',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
